version: "3.9"

services:
  ubuntu18.04-cuda11.3.1:
    image: thecanadianroot/opencv-cuda:ubuntu18.04-cuda11.3.1-opencv3.4.14
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UBUNTU=18.04
        - CUDA=11.3.1
        - OPENCV=3.4.14

  ubuntu20.04-cuda11.3.1:
    image: thecanadianroot/opencv-cuda:ubuntu20.04-cuda11.3.1-opencv4.5.2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UBUNTU=20.04
        - CUDA=11.3.1
        - OPENCV=4.5.2