name: OpenCV CUDA Docker

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ubuntu18_04-cuda10_2-opencv3_4_14:
    name: Build OpenCV 3.4.14 with CUDA 10.2 on Ubuntu 18.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: thecanadianroot/opencv-cuda-docker:ubuntu18.04-cuda10.2-opencv3.4.14
          build-args: UBUNTU=18.04, CUDA=10.2, OPENCV=3.4.14

  build-ubuntu20_04-cuda11_3-opencv4_5_2:
    name: Build OpenCV 4.5.2 with CUDA 11.3.0 on Ubuntu 20.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: thecanadianroot/opencv-cuda-docker:ubuntu20.04-cuda11.3.0-opencv4.5.2
          build-args: UBUNTU=20.04, CUDA=11.3.0, OPENCV=4.5.2
